---
title: "MID_EXAM"
author: "Gantungalag"
date: "4/27/2020"
output: html_document
---

```{r}
#rm(list=ls())
library(quantmod)
library(plyr)
library(fBasics)
library(tidyverse)
library(openair)
con = gzcon(url('https://github.com/systematicinvestor/SIT/raw/master/sit.gz', 'rb'))
source(con)
close(con)
library(xts)
```

```{r}
#Download ETF daily data from yahoo with ticker names of SPY, QQQ, EEM, IWM, EFA, TLT, IYR, GLD from 2010 to 2018. 
tickers<-c("SPY", "QQQ", "EEM", "IWM", "EFA", "TLT", "IYR", "GLD" )
data.env<-new.env()
getSymbols(tickers ,from = "2010/01/01", to = "2018/12/31", env = data.env, auto.assign = TRUE)
l_ply(tickers, function(sym) try(getSymbols(sym ,from = "2010/01/01" ,to = "2018/12/31", env=data.env, auto.assign = TRUE), silent=T))
stocks <- tickers[tickers %in% ls(data.env)]
stocks
data <- xts()
for(i in seq_along(stocks)) 
{
  symbol <- stocks[i]
  data <- merge(data, Ad(get(symbol, envir=data.env)))}

head(data)
tail(data)

```


```{r}
#Q1. Use the data to calculate daily returns. Find their means, median, 1-st quartile, third-quartile, standard deviation, skewness and kurtosis.


SPYreturn = dailyReturn(data$SPY.Adjusted)
QQQreturn = dailyReturn(data$QQQ.Adjusted)
EEMreturn = dailyReturn(data$EEM.Adjusted)
IWMreturn = dailyReturn(data$IWM.Adjusted)
EFAreturn = dailyReturn(data$EFA.Adjusted)
TLTreturn = dailyReturn(data$TLT.Adjusted)
IYRreturn = dailyReturn(data$IYR.Adjusted)
GLDreturn = dailyReturn(data$GLD.Adjusted)
dailyreturns = merge(SPYreturn,QQQreturn,EEMreturn,IWMreturn,EFAreturn,TLTreturn,IYRreturn,GLDreturn  )
colnames(dailyreturns)
names(dailyreturns)[names(dailyreturns) =="daily.returns" ] <- "SPY"
names(dailyreturns)[names(dailyreturns) =="daily.returns.1" ] <- "QQQ"
names(dailyreturns)[names(dailyreturns) =="daily.returns.2" ] <- "EEM"
names(dailyreturns)[names(dailyreturns) =="daily.returns.3" ] <- "IWM"
names(dailyreturns)[names(dailyreturns) =="daily.returns.4" ] <- "EFA"
names(dailyreturns)[names(dailyreturns) =="daily.returns.5" ] <- "TLT"
names(dailyreturns)[names(dailyreturns) =="daily.returns.6" ] <- "IYR"
names(dailyreturns)[names(dailyreturns) =="daily.returns.7" ] <- "GLD"
head(dailyreturns)
summary = summary(data)
summary
sd = sd(data)
sd
skewness = apply(data, 2, skewness)
skewness
kurtosis = apply(data, 2, kurtosis)
kurtosis
```


```{r}
#Q2. Based on daily returns and their covariance matrix, and compute weights of minimum variance portfolio (MVP). 
Sigma.weekly = cov(dailyreturns)
Sigma.weekly
ones = rep(1,8)     
one.vec = matrix(ones, ncol=1)
a.weekly = inv(Sigma.weekly)%*%one.vec
b.weekly = t(one.vec)%*%a.weekly
mvp.w.weekly =a.weekly / as.numeric(b.weekly)
mvp.w.weekly
```

```{r}
#Q3. By 2, now use year 2010-2013 data to calculate weekly returns and their covariance matrix, and compute weights of minimum variance portfolio (MVP).
data.weekly <- data[endpoints(data, on="weeks", k=1), ]
#selectByDate(data.weekly,start = "2010/01/01",end = "2013/12/31")
head(data.weekly)
tail(data.weekly)

Sigma.weekly = cov(data.weekly)
Sigma.weekly
ones = rep(1,8)     
one.vec = matrix(ones, ncol=1)
a.weekly = inv(Sigma.weekly)%*%one.vec
b.weekly = t(one.vec)%*%a.weekly
mvp.w.weekly =a.weekly / as.numeric(b.weekly)
mvp.w.weekly


```


```{r}
#Q4. By 3, now use year 2010-2013 data to calculate monthly returns and their covariance matrix, and compute weights of minimum variance portfolio (MVP). 
data.monthly <- data[endpoints(data, on="months", k=1), ]
#selectByDate(data.monthly,start = "2010/01/01",end = "2013/12/31")
head(data.monthly)
tail(data.monthly)


Sigma.monthly = cov(data.monthly)
Sigma.monthly
ones = rep(1,8)     
one.vec = matrix(ones, ncol=1)
a.monthly = inv(Sigma.monthly)%*%one.vec
b.monthly = t(one.vec)%*%a.monthly
mvp.w.monthly =a.monthly / as.numeric(b.monthly)
mvp.w.monthly

```

```{r}
#Q5. Compute optimal weights for Q3 and Q4 when short selling is not allowed.
n <- length(tickers)
constraints <- new.constraints(n, lb = -Inf, ub= +Inf)
# sum x.i = 1
constraints <- add.constraints(rep(1,n) , 1 , type = "=", constraints)
ia <- create.historical.ia(data.weekly, 250)
weight <- min.risk.portfolio(ia, constraints)
weight
```


```{r}
#Q6. Go to Fama French 3 factors data website:Download Fama/French 3 factor returns’ monthly data (Mkt-RF, SMB and HML). 
#a.	Compute its mean and covariance matrix using monthly data from 2010-2018.
library(readxl)
FAMA <- read_excel("FAMA.xlsx")
FAMA.ret<-FAMA %>% select(c(2,3,4,5))/100
glimpse(FAMA.ret)
FAMA1 = FAMA %>% select(c(2,3,4,5))
FAMA.mean = apply(FAMA1, 2, mean)
FAMA.cov = cov(FAMA1)
```


```{r}
#Q7.Based on CAPM model, compute covariance matrix for the 8-asset portfolio by using past 60 monthly returns from 2014/01 - 2018/12.

Mkt_RF <- FAMA.ret[, 1]
fit3 = lm(formula = cbind(SMB , HML)~Mkt_RF, data=FAMA.ret)
sigF3 = as.matrix(var(cbind( 
                            FAMA.ret$SMB, 
                            FAMA.ret$HML)))
bbeta3 = as.matrix(fit3$coefficients)
bbeta3 = bbeta3[-1,]
bbeta3 = as.matrix(bbeta3)
N <- dim(FAMA.ret)[1]
sigeps3 = crossprod(fit3$residuals)/(N-4)
sigeps3 = diag(diag(sigeps3))
#cov_3f = sigF3*t(bbeta3) *(bbeta3) + sigeps3
#cov_3f

X.3 = cbind(ones, FAMA.ret$Mkt_RF, FAMA.ret$SMB, FAMA.ret$HML)
b_hat.3 = solve(t(X.3)%*%(X.3))%*%t(X.3)%*%as.matrix(FAMA.ret)
E_hat.3 = as.matrix(FAMA.ret) - X.3%*%b_hat.3
b_hat.3 = as.matrix(b_hat.3[-1,])
diagD_hat.3 = diag(t(E_hat.3)%*%E_hat.3)/(N-4)
#cov_3f.3 = as.matrix(b_hat.3)*sigF3%*%b_hat.3 + diag(diagD_hat.3) 
#cov_3f.3
```